# Generated by Django 3.2.7 on 2021-10-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_campus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="course",
            name="holder_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
